### ISSUE TITLE
Resolving Conflicts triggers webhooks

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [couchbaselabs/sync_gateway#5576]
I'm using CSG 2.8.3 and noticed that when resolving conflicts by deleting non-winning revisions, a corresponding webhook is triggered: each time I delete a non-winning revision, my webhook receives the latest revision over and over again, even though this revision did not change. Is this behavior intended? I, personally, think this is confusing and I wouldn't expect this to happen. I noticed it by chance as resolving conflicts broke our business logic.

**Comment by hermitdemschoenenleben** [comment]
Here's an example of why the current behavior isn't nice:

My app features private chats. When a user writes a message to another user, a webhook triggered by the message document sends a push message to the recipient. If there are conflicting message docs, there is no way to resolve these conflicts without repeatedly sending these push messages, because in the webhooks handler I can't decide whether the message was just created or whether a conflict was resolved.

**Comment by adamcfraser** [comment]
I believe there's an existing webhook config value that can be used to only trigger webhooks when the winning revision changes, by setting the following property in the document change event configuration:
```
"options": {
   "winning_rev_only":true
 }
```

It looks like this option isn't included in our docs - let me know if that works for you, and I can follow up to get it into the docs.

**Comment by hermitdemschoenenleben** [comment]
thank you very much, this option works like a charm! :) Would be great if it was documented :+1:

**Comment by bbrks** [comment]
Filed an issue to get this documented

https://issues.couchbase.com/browse/DOC-10217
