### ISSUE TITLE
Where is the function to remove a role from a user?

### ISSUE THREAD

**Issue by 1cedsoda** [couchbaselabs/sync_gateway#5900]
[https://github.com/couchbase/sync_gateway/blob/1af4db20de976ecf7a884a7435137a50e6e49c0f/channels/sync_runner.go](https://github.com/couchbase/sync_gateway/blob/1af4db20de976ecf7a884a7435137a50e6e49c0f/channels/sync_runner.go)

**Comment by adamcfraser** [comment]
Dynamic access grants (performed via the sync function) are associated with the revision of the document performing the grant, and are recomputed each time the document is updated.  To revoke a role grant performed by a document, update that document such that the document no longer grants that role.
