### ISSUE TITLE
Buggy usage of canSeeCollectionChannelSince

### ISSUE THREAD

**Issue by TheCrazyT** [couchbaselabs/sync_gateway#6550]
As seen on line:

https://github.com/couchbase/sync_gateway/blob/61a63e3521ada9bb90c443c0f37cc144ef1fd06f/auth/user.go#L659

Theoretically you would expect that later the function canSeeChannelSince of the userImpl will get used.
But thats not the case, because it will use the function inside the roleImpl (because the canSeeCollectionChannelSince inside roleImpl will use the roleImpl-function).
The result of that is, that role-channels are not included.

I also believe that this causes the problem I mentioned at https://github.com/couchbase/couchbase-lite-java-ce-root/issues/22.
(setting a channel on replication and having roles with channels can lead to unexpected behaviour)

**Comment by TheCrazyT** [comment]
Theoretically this means that  user_collection_access.go would need its own canSeeCollectionChannelSince,but I'm not shure how to write it in go with minimal redundant code .

**Comment by gregns1** [comment]
Thanks for the report! The fix has been carried out and it will be in the next release (3.1.2).
